const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const veil=$("#veil"), ambience=$("#ambience"), thought=$("#thought"); let world="untamed", open=false, busy=false, thoughtTimer;
const sets={
untamed:{hero:"wangxian_the_untamed_and_theres_a_waterfall_idk.jpg",laugh:"wei_wuxian_smilling_the_untamed.jpg",soft:"lan_zhan_giving_wei_wuxian_a_rabbit_the_untamed.jpg",song:"guiquin_or_whatever_the_thing_lan_zhan_plays_the_untamed.jpg",choice:"tht_one_sad_scene_the_untamed(psst.its.wei.wuxian.deciding.to save.the.rest.of.wen.clan).jpg",river1:"lan_wangji_looking_at_wei_wuxian_make_a_wish_the_untamed.jpg",river2:"lan_wangji_givving_wei_wuxian_a_lotus_seed_the_untamed.jpg",river3:"lan_zhan_carrying_yilling_lauzo_on_his_back_the_untamed.jpg",walk:"wangxian_the_untamed_walking_side_by_side_walking_away_from_the_camera.jpg"},
donghua:{hero:"wangxian_bg_but_its_anime_ver.jpg",laugh:"wei_wuxian_making_lan_zhan_smile_in_the_anime.jpg",soft:"wangxian_rabbits_extra_cute.jpg",song:"wangxian_scene_anime.jpg",choice:"wangxian_in_red_finally_proper_anime_ver.jpg",river1:"wangxian_anime_fanart.jpg",river2:"wangxian_fanart_very_majestic.jpg",river3:"another_wangxian_fanart_bg.jpg",walk:"wangxian_anime.jpg"}};
const A="assets/images/";
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function show(id){$$(".screen").forEach(s=>{let yes=s.id===id;s.classList.toggle("active",yes);s.setAttribute("aria-hidden",String(!yes))});scrollTo(0,0)}
async function drift(id,beat=700){if(busy)return;busy=true;veil.classList.add("in");await sleep(1500);show(id);await sleep(beat);veil.classList.remove("in");await sleep(1500);busy=false}
$("[data-go]").onclick=()=>drift("world",700);$("[data-gone]").onclick=()=>drift("gone",1800);
$$("[data-world]").forEach(b=>b.onclick=async()=>{world=b.dataset.world;document.body.dataset.world=world;applyImages();$("#sealInput").placeholder=world==="donghua"?"name the animation...":"name the drama...";await drift("seal",800);setTimeout(()=>$("#sealInput").focus(),500)});
const normalize=v=>v.trim().toLowerCase().replace(/[\s_-]+/g,""); const passwords={donghua:["modaozushi","魔道祖师","魔道祖師"],untamed:["theuntamed","陈情令","陳情令"]};
$("#sealForm").onsubmit=async e=>{e.preventDefault();let input=$("#sealInput"),msg=$("#sealMessage");if(!(passwords[world]||[]).map(normalize).includes(normalize(input.value))){msg.textContent=["Not quite.","That doesn't sound right.","..."][Math.floor(Math.random()*3)];input.value="";input.focus();return}msg.textContent="";await drift("threshold",900);await sleep(2700);veil.classList.add("in");await sleep(1500);show("memory");await sleep(2100);veil.classList.remove("in");open=true;ambience.volume=0;ambience.play().catch(()=>{});let v=0,fade=setInterval(()=>{v=Math.min(.32,v+.015);ambience.volume=v;if(v>=.32)clearInterval(fade)},180);observe();scheduleThought();busy=false};
function applyImages(){let set=sets[world];$$("[data-img]").forEach(el=>{let f=set[el.dataset.img];if(f)el.src=A+f});$(".seal-image").style.backgroundImage=`url("${encodeURI(A+set.hero)}")`}
applyImages();
$("#sound").onclick=async()=>{if(ambience.paused){await ambience.play().catch(()=>{});$("#sound").textContent="sound, remembered"}else{ambience.pause();$("#sound").textContent="silence"}};
$("#noteButton").onclick=()=>{$("#noteReply").textContent="You did.";$("#noteButton").style.opacity=".2"};
$("#songButton").onclick=async()=>{await ambience.play().catch(()=>{});$("#sound").textContent="sound, remembered";$("#songButton").textContent="there it is."};
const thoughts=["Lan Zhan.","Wei Ying.","Don't skip this part.","You remember what happens next.","Was it always this quiet?","Come back later.","..."];
function flash(){if(!open)return;thought.textContent=thoughts[Math.floor(Math.random()*thoughts.length)];thought.style.setProperty("--x",`${10+Math.random()*80}vw`);thought.style.setProperty("--y",`${12+Math.random()*76}svh`);thought.classList.remove("flash");void thought.offsetWidth;thought.classList.add("flash");setTimeout(()=>thought.classList.remove("flash"),400)}
function roll(){if(Math.random()<.05)flash()} function scheduleThought(){clearTimeout(thoughtTimer);thoughtTimer=setTimeout(()=>{roll();scheduleThought()},90000+Math.random()*150000)}
function observe(){let io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");if(e.target.id==="ending")e.target.classList.add("play")}}),{threshold:.14});$$(".reveal,#ending").forEach(el=>io.observe(el))}
const quiz=[{q:"What returns to you first?",a:[["A melody.","lan"],["A laugh.","wei"],["A place that used to be home.","jiang"],["A quiet act of kindness.","wen"]]},{q:"You know the ending. Why do you stay?",a:[["Devotion changed the meaning of it.","lan"],["Joy survived somehow.","wei"],["Grief deserves to be remembered.","jiang"],["Small choices mattered.","wen"]]}],results={lan:"Lan Wangji stayed with you. Maybe it was the quiet. Maybe it was everything the quiet contained.",wei:"Wei Wuxian stayed with you. Some people remain as laughter first, and ache second.",jiang:"Jiang Cheng stayed with you. Home, grief, anger—some memories refuse to become simple.",wen:"Wen Ning stayed with you. Perhaps you remembered the gentleness that survived."};let qi=0,scores={lan:0,wei:0,jiang:0,wen:0};
$("#quizStart").onclick=()=>{$("#quizStart").classList.add("hidden");$("#quizBox").classList.remove("hidden");renderQuiz()};
function renderQuiz(){let item=quiz[qi];$("#quizQuestion").textContent=item.q;$("#quizAnswers").innerHTML="";item.a.forEach(([label,key])=>{let b=document.createElement("button");b.textContent=label;b.onclick=()=>{scores[key]++;qi++;qi<quiz.length?renderQuiz():finishQuiz()};$("#quizAnswers").appendChild(b)})}
function finishQuiz(){$("#quizBox").classList.add("hidden");let winner=Object.entries(scores).sort((a,b)=>b[1]-a[1])[0][0];$("#quizResult").textContent=results[winner];$("#quizResult").classList.remove("hidden")}
$("#ending").addEventListener("animationend",e=>{if(e.target.classList.contains("e4"))setTimeout(async()=>{veil.classList.add("in");await sleep(1800);show("opening");veil.classList.remove("in");open=false;ambience.pause();ambience.currentTime=0},2200)});
